import type { Metadata } from 'next';
import Image from 'next/image';
import React from 'react';
import { Layout, Button } from 'antd';
import { Header, Footer, Content } from 'antd/lib/layout/layout';
import { ApiOutlined, GithubOutlined } from '@ant-design/icons';
import Link from 'next/link';
import './globals.css';
import RS from '../../public/rss-logo.svg';
import style from './layout.module.css';
import SwitchLang from '@/components/switchLang/switchLang';

export const metadata: Metadata = {
  title: 'Rest GraphQL Client',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Layout className={style.layout}>
          <Header className={`${style.header} issticky`}>
            <ApiOutlined style={{ fontSize: '150%' }} />
            <Link href="/">Home</Link>
            <SwitchLang />
            <Button>Sign Out </Button>
          </Header>
          <Content className={style.content}>{children}</Content>
          <Footer className={style.footer}>
            <Link href="https://rs.school/">
              <Image src={RS} alt="RSSchool" width={20}></Image>
            </Link>
            <span>2024</span>
            <div className={style.github}>
              <Link href="https://github.com/zytsev">
                <GithubOutlined />
                Evgeny
              </Link>
              <Link href="https://github.com/petru6e4ka">
                <GithubOutlined />
                Anastasiia
              </Link>
              <Link href="/">
                <GithubOutlined />
                Ivan
              </Link>
            </div>
          </Footer>
        </Layout>
      </body>
    </html>
  );
}
